reorganized the first section, in line with MEG and EEG spec
choldgraf/bids-specification pull request #2
Opened 2019-01-09 13:14 UTC by robertoostenveld

I started making the format more consistent with the MEG and EEG sections of the specification. I especially think that the conversion of the EEG spec by @sappelhoff is a good template for the format. Also,many shorter sections of text can be shared (i.e. copied) from the EEG spec, since they should be the same.

2019-01-09 13:14 UTC, robertoostenveld commented
Please consider this instead of PR #1

2019-01-09 15:36 UTC, choldgraf commented
Thanks very much for the PR @robertoostenveld :-) I agree w/ you that it's better to standardize these sections and I agree that @sappelhoff did a great job in that PR, I just hadn't gotten around to taking another pass through this one. I'll give it a closer look today in case I have comments!

2019-01-09 15:40 UTC, robertoostenveld commented
I could help getting the other sections in the same format as well.

2019-01-09 17:20 UTC, choldgraf commented
if you have a moment, then please feel free to do so. The PR is currently just my first pass at converting the google doc into markdown format, but I haven't spent a lot of time thinking about overall organization and how it should fit in with the current spec. My time for BIDS this week is gonna be spent on finalizing the draft for submission, so if you have the cycles please feel free to improve this!

2019-01-10 12:18 UTC, robertoostenveld commented
@choldgraf can you please review the result of my reformatting and - if ok - merge it into your `bep010` branch? It will then be part of https://github.com/bids-standard/bids-specification/pull/118 and can be reviewed again by @chrisfilo and others.

2019-01-10 16:38 UTC, choldgraf commented
Sounds good - I was gonna give it a review but just noticed that you made a commit since your last message...would you like me to hold off a bit? Or ready for review now?

2019-01-10 16:40 UTC, robertoostenveld commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +## Electrical stimulation
I think this addresses Q1 of https://github.com/bids-standard/bids-specification/issues/61

2019-01-10 16:52 UTC, robertoostenveld commented
sorry, the commit ~20 minutes ago was not planned, just me trying out this prettier.io application that ChrisG mentioned in another PR I was working on. Please go ahead, I will not touch it any more!

2019-01-10 17:01 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +**Allowed Formats**
```suggestion
**Accepted Formats**
```

2019-01-10 17:26 UTC, choldgraf requested changes
Took a pass through these changes - in general I think that the text and layout are both much improved, thanks very much! I added a few comments and suggested changes here and there. Let me know what you think about those and we can merge once these are resolved.

I didn't do anything with the text underneath your `=====` message at the bottom...I think that'll be easier to look through outside of the GitHub UI so we can spot-check that in the other PR.

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +**Allowed Formats**
just for consistency's sake since we use this word above

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +The original data format is especially valuable in case conversion elicits the
```suggestion
The data format in which the data was originally stored is especially valuable in case conversion elicits the
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +MAY be included alongside the original EEG data in the
I guess it's fine to say EEG since the intracranial is implied?

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +manufacturer specific data files in the sidecar JSON file. Other relevant files
```suggestion
manufacturer-specific data files in the sidecar JSON file. Other relevant files
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +For proper documentation of iEEG recording metadata it is important to
```suggestion

### Terminology: Electrodes vs. Channels

For proper documentation of iEEG recording metadata it is important to
```
What do you think about this, just to make the page easier to parse?

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +differential amplifier and analog-to-digital converter that result in a
```suggestion
differential amplifier and analog-to-digital converter that results in a
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +-   Electrode = A single point of contact between the acquisition system and the
```suggestion
-   **Electrode** = A single point of contact between the acquisition system and the
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +-   Channel = A single analog-to-digital converter in the recording system that
```suggestion
-   **Channel** = A single analog-to-digital converter in the recording system that
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +### Sidecar JSON document (`*_ieeg.json`)
```suggestion

### Sidecar JSON document (`*_ieeg.json`)
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +| SoftwareFilters    | REQUIRED. List of temporal software filters applied or ideally key:value pairs of pre-applied filters and their parameter values. (n/a if none). E.g., “{'HighPass': {'HalfAmpli
```suggestion
| SoftwareFilters    | REQUIRED. List of temporal software filters applied or ideally key:value pairs of pre-applied filters and their parameter values. (n/a if none). E.g., `{'HighPass': {'HalfAmplitudeCutOffHz': 1, 'RollOff: '6dB/Octave'}}`.                                                                                                                                                                                            |
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +Generic fields MUST be present:
```suggestion
**Generic fields**

MUST be present:
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +SHOULD be present: For consistency between studies and institutions, we
```suggestion
**SHOULD be present**

For consistency between studies and institutions, we
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +Specific iEEG fields MUST be present:
```suggestion
**Specific iEEG fields**

MUST be present:
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +Specific iEEG fields SHOULD be present:
```suggestion
**SHOULD be present**
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +Specific iEEG fields MAY be present:
```suggestion
**MAY be present**
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +The columns of the Channels description table stored in \*\_channels.tsv are:
```suggestion
The columns of the Channels description table stored in `*_channels.tsv` are listed below.
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +MUST be present:
```suggestion
**MUST be present**
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +SHOULD be present:
```suggestion
**SHOULD be present**
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +LT01  ECOG  μV    10000             3000       0.11        n/a   LTG   mastoid   lateral_temporal_surface good   n/a
```suggestion
LT01  ECOG  μV    10000              3000       0.11        n/a   LTG   mastoid   lateral_temporal_surface good   n/a
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +LT02  ECOG  μV    10000              3000       0.11        n/a   LTG   mastod   lateral_temporal_surface bad    brokenn
```suggestion
LT02  ECOG  μV    10000              3000       0.11        n/a   LTG   mastod    lateral_temporal_surface bad    broken
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +and EEG modality; however, only iEEG specific types are listed here):
It seems like we're listing more than just the iEEG specific types, no? Perhaps we should put them in bold? Or remove the non-iEEG specific types (like `EEG`)?

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +`*_coordsystem.json`. **If an `*_electrodes.tsv` file is specified, a
```suggestion
`*_coordsystem.json`.

**If an `*_electrodes.tsv` file is specified, a
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +`*_coordsystem.json` file MUST be specified as well**. The order of the required
```suggestion
`*_coordsystem.json` file MUST be specified as well**.

The order of the required
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +MUST be present:
```suggestion
**MUST be present**

```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +SHOULD be present:
```suggestion
**SHOULD be present**
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +MAY be present:
```suggestion
**MAY be present**
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +standard space as specified in BIDS Appendix VIII: preferred names of Coordinate
```suggestion
standard space as specified in [BIDS Appendix VIII: preferred names of Coordinate
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +systems, such as ACPC).
```suggestion
systems](../99-appendices/08-coordinate-systems), such as ACPC).
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +n/a), then the positions in this file must correspond to the locations expressed
```suggestion
`n/a`), then the positions in this file must correspond to the locations expressed
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +### Multiple coordinate systems
```suggestion

### Multiple coordinate systems
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +in which electrode positions are interpreted, see [TODO: link] BEP003 - Common
```suggestion
in which electrode positions are interpreted, see [BEP003 - Common
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +Derivatives. Examples include:
```suggestion
Derivatives](../06-extensions). Examples include:
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +anatomical features or landmarks (such as sulcal structure), fiducials. Photos
```suggestion
anatomical features or landmarks (such as sulcal structure), and fiducials. Photos
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +Example of the operative photo of ECoG electrodes (here an annotated example in
```suggestion
Example of the operative photo of ECoG electrodes (here is an annotated example in
```

2019-01-10 17:26 UTC, choldgraf commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +called electrical*stimulation*<label>, with labels chosen by the researcher and
```suggestion
called `electrical*stimulation*<label>`, with labels chosen by the researcher and
```

2019-01-10 20:35 UTC, robertoostenveld commented on src/04-modality-specific-files/06-intracranial-electroencephalography.md
> +## Electrical stimulation
@dorahermes and @choldgraf are you ok with this, or is more needed on electrical stimulation?

2019-01-10 20:51 UTC, robertoostenveld commented
I think I resolved all comments. I also deleted the remainders section and pasted it into a separate document. See https://docs.google.com/document/d/1Ab-cmX5FkxechrOR8ZgnBZsRrxDwcHMKunWLx_KQPZQ/edit?usp=sharing

I propose you merge my PR with your branch, so that others can see this in your https://github.com/bids-standard/bids-specification/pull/118. 

@sappelhoff, is it an idea that you merge the BEP010 branch PR for iEEG with BEP006 PR for EEG, so that a single branch remains to be merged with the main spec? I think it will be easier to finalize the two modality-specific sections (and some updates to MEG) if all are in a single branch.

2019-01-11 01:15 UTC, merged

2019-01-11 01:16 UTC, choldgraf commented
perfect, thanks - I'll merge this in with the branch and we can start iterating in the other PR, this is much better!

@sappelhoff I'm happy to make this PR to your branch if that's a better way to move forward.